vich_uploader:
    db_driver: orm

    mappings:
        upload_tarif:
            uri_prefix: uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: vich_uploader.namer_origname

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
